backend:
  name: git-gateway
  branch: master
media_folder: assets/images

collections:
  - name: "Site"
    label: Site
    files:
      - label: "Information"
        name: "config"
        file: "_config.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: "Cover Photo", name: "cover", widget: "image" }
          - { label: "Logo Photo", name: "logo", widget: "image" }

  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      # Metadata
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - {
          label: "Navigation",
          name: "navigation",
          widget: "hidden",
          default: True,
        }
      - {
          label: "Class",
          name: "class",
          widget: "hidden",
          default: "post-template",
        }
      - {
          label: "Sub Class",
          name: "subclass",
          widget: "hidden",
          default: "post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Cover", name: "cover", widget: "image" }
  - name: "authors"
    label: "Authors"
    files:
      - label: "Authors"
        name: authors
        file: _data/authors.yml
        fields:
          - label: Nikita
            name: nikita
            widget: object
            fields:
              - { label: Name, name: name, widget: hidden, default: nikita }
              - { label: Name, name: username, widget: hidden, default: nikita }
              - {
                  label: Name,
                  name: display_name,
                  widget: string,
                  hint: "Full Name",
                }
              - { label: Picture, name: picture, widget: image }
              - { label: Bio, name: bio, widget: string }
              - { label: Facebook, name: facebook, widget: string }
              - {
                  label: Cover Photo,
                  name: cover,
                  widget: image,
                  default: False,
                }
              - {
                  label: Location,
                  name: location,
                  widget: string,
                  hint: "City,State",
                }
